# whether to deny everything if an error occurs within event handling
safe-mode: true
# whether to only respect manage.chunkload flag while any member of the region is online
chunkload-while-online-only: true

# note: do not use remote databases with high latency because it will slow down worldmod
database:
  type: h2
  url: jdbc:h2:file:./worldmod.h2
  username: sa
  password:
# if your libmod database is local, you can simply comment the database block and set 'database: inherit' instead
#database: inherit

# configure wand items
wand:
  selection: minecraft:stick
  lookup: minecraft:blaze_rod

# configure world logging behaviour
logging:
  # set to 'true' to skip all logging entries that have no player involved
  skip-non-player: true
  # list of flags to skip on logging; wildcards supported
  skip:
    # these defaults reduce logs that barely carry any useful information
    - move
    - interact
    # these defaults exist purely to reduce garbage data when setting 'skip-non-player: false'
    - grow
    - spread
    - spawn.mobs
