# configure wand items
wand:
  selection: minecraft:stick
  lookup: minecraft:blaze_rod

# configure world logging behaviour
logging:
  # set to 'true' to skip all logging entries that have no player involved
  skip-non-player: true
  # list of flags to skip on logging; wildcards supported
  skip:
    # these defaults reduce logs that barely carry any useful information
    - move
    - interact
    # these defaults exist purely to reduce garbage data when setting 'skip-non-player: false'
    - grow
    - spread
    - spawn.mobs
