name: WorldMod
version: '0.1.0'
description: World Protection Mod, because EngineHub people are assholes
main: com.ampznetwork.worldmod.spigot.WorldMod$Spigot
api-version: '1.18'
load: STARTUP
website: https://github.com/AMPZNetwork/WorldMod
commands:
  reload:
    description: Reloads Configuration
    permission: worldmod.reload
  select:
    aliases: sel
    description: Modify selected Area
    permission: worldmod.selection
  position:
    aliases: pos
    description: Modify selected Area
    permission: worldmod.selection
  claim:
    description: Interact with your Claim
    permission: worldmod.claim
  region:
    description: Interact with Regions
    permission: worldmod.region
