name: WorldMod
version: '0.1.0'
description: World Protection Mod, because EngineHub people are assholes
main: com.ampznetwork.worldmod.spigot.WorldMod$Spigot
api-version: '1.18'
load: STARTUP
website: https://github.com/AMPZNetwork/WorldMod
depend:
  - LibMod
commands:
  reload:
    description: Reloads Configuration
    permission: worldmod.reload
  select:
    aliases: sel
    description: Modify selected Area
    permission: worldmod.selection
  position:
    aliases: pos
    description: Modify selected Area
    permission: worldmod.selection.pos
  claim:
    description: Interact with your Claim
    permission: worldmod.claim
  region:
    description: Interact with Regions
    permission: worldmod.region
  lookup:
    description: Lookup logged world events
    permission: worldmod.lookup
  wand:
    description: Toggle wand item
    permission: worldmod.wand
permissions:
  worldmod:
    description: WorldMod root permission node
    default: false
    children:
      worldmod.reload:
        description: Permission for the /worldmod:reload command
        default: false
      worldmod.selection:
        description: Permission for making and interacting with selections
        default: true #
        children:
          worldmod.selection.pos:
            description: Permission to use the /pos commands to make a selection
          worldmod.selection.wand:
            description: Permission to use the selection wand item
            default: true
      worldmod.claim:
        description: Permission for making and interacting with claims
        default: true
      worldmod.region:
        description: Permission for administrating regions and creating common claims
        default: false
      worldmod.lookup:
        description: Permission for looking up logged world events
        default: false
        children:
          worldmod.lookup.wand:
            description: Permission to use the lookup wand item
            default: false
      worldmod.wand:
        description: Permission for toggling the wand item
        default: true
        children:
          worldmod.wand.selection:
            description: Permission for toggling the selection wand item
            default: true
          worldmod.wand.lookup:
            description: Permission for toggling the lookup wand item
            default: false
