server:
  port: 42065
spring:
  # bean overriding
  main:
    allow-bean-definition-overriding: true
  # database config
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: false
    hibernate.ddl-auto: update
  datasource:
    hikari:
      auto-commit: true
      max-lifetime: 360_000
logging:
  level:
    root: info
    cron: debug
    screen: warn
    org.comroid: debug
    org.hibernate.SQL: info
