server:
  port: 42064
  # sessions
  servlet:
    session:
      timeout: 7d
spring:
  session:
    jdbc:
      initialize-schema: embedded
      table-name: sessions
  # bean overriding
  main:
    allow-bean-definition-overriding: true
  # database config
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: false
    hibernate.ddl-auto: update
  datasource:
    hikari:
      auto-commit: true
      max-lifetime: 360_000
  # mvc config
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
logging:
  level:
    root: info
    cron: debug
    screen: warn
    org.comroid: debug
