name: Upload Artifacts to Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Upload Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
          path: WorldMod

      - name: Clone japi repository
        uses: actions/checkout@v2
        with:
          repository: comroid-git/japi
          path: japi
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build Artifacts
        run: cd WorldMod && ./gradlew simplifyArtifact

      - name: Upload API JAR to Release
        id: upload-api-assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: WorldMod/build/libs/WorldMod-api.jar
          asset_name: "WorldMod-api-${{ github.event.release.tag_name }}.jar"
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Spigot Plugin to Release
        id: upload-spigot-assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: WorldMod/build/libs/WorldMod-spigot.jar
          asset_name: "WorldMod-spigot-${{ github.event.release.tag_name }}.jar"
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Forge Mod to Release
        id: upload-forge-assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: WorldMod/build/libs/WorldMod-forge.jar
          asset_name: "WorldMod-forge-${{ github.event.release.tag_name }}.jar"
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Fabric Mod to Release
        id: upload-fabric-assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: WorldMod/build/libs/WorldMod-fabric.jar
          asset_name: "WorldMod-fabric-${{ github.event.release.tag_name }}.jar"
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
